version: '3.8'

networks:
  gog_network:
    driver: bridge

volumes:
  minio_data:
  es_data:
  db_data:
  traefik_acme:
  traefik_logs:

services:

  # ============================================
  # TRAEFIK - Reverse Proxy & SSL
  # ============================================
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - gog_network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - traefik_acme:/acme
      - traefik_logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      
      # Basic Auth for Dashboard
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}"

  # ============================================
  # FRONTEND - React Application
  # ============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - gog_network
    env_file:
      - .env
    environment:
      - API_BASE_URL=${API_URL}
      - IMAGE_BASE_URL=${CMS_URL}
      - MINIO_BASE_URL=${MINIO_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=8081"

  # ============================================
  # BACKEND - FastAPI
  # ============================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    networks:
      - gog_network
    env_file:
      - .env
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS}
      - MINIO_PUBLIC_URL=${MINIO_URL}
      - DRUPAL_PUBLIC_URL=${CMS_URL}
      - FRONTEND_PUBLIC_URL=${FRONTEND_URL}
    depends_on:
      - elasticsearch
      - minio
      - drupal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  # ============================================
  # DRUPAL - Headless CMS
  # ============================================
  drupal:
    build:
      context: ./drupal-docker
      dockerfile: Dockerfile
    container_name: drupal
    restart: unless-stopped
    networks:
      - gog_network
    volumes:
      - ./drupal-docker/drupal_t:/var/www/html
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drupal.rule=Host(`${CMS_DOMAIN}`)"
      - "traefik.http.routers.drupal.entrypoints=websecure"
      - "traefik.http.routers.drupal.tls.certresolver=letsencrypt"
      - "traefik.http.services.drupal.loadbalancer.server.port=80"

  # ============================================
  # MARIADB - Drupal Database
  # ============================================
  db:
    image: mariadb:10.5
    container_name: drupal_db
    restart: unless-stopped
    networks:
      - gog_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./drupal-docker/db.sql:/docker-entrypoint-initdb.d/db.sql

  # ============================================
  # MINIO - Object Storage
  # ============================================
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    networks:
      - gog_network
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    labels:
      - "traefik.enable=true"
      
      # MinIO API
      - "traefik.http.routers.minio-api.rule=Host(`${MINIO_DOMAIN}`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      
      # MinIO Console
      - "traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_DOMAIN}`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"



  # ------------------------------------------------------------
  # One-time file uploader (runs on same network as MinIO)
  # ------------------------------------------------------------
#  uploader:
#    image: python:3.12-slim
#    working_dir: /app
#    volumes:
#      - ./:/app                      # repo
#      - ./DocumentsToUpload:/data    # host folder -> /data
#    networks:
#      - gog_network
#    depends_on:
#      - minio
#    command: >
#      sh -c "pip install --no-cache-dir -r requirements.txt &&
#             python uploader.py"


  # ============================================
  # ELASTICSEARCH - Search Engine
  # ============================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - gog_network
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`${SEARCH_DOMAIN}`)"
      - "traefik.http.routers.elasticsearch.entrypoints=websecure"
      - "traefik.http.routers.elasticsearch.tls.certresolver=letsencrypt"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"

  # ============================================
  # PGADMIN - PostgreSQL Admin (if needed)
  # ============================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    networks:
      - gog_network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${CONTACT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`${DB_DOMAIN}`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
